
services:
  service-recipe:
    container_name: service-recipe
    image: service:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db-postgre
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db-postgre
    healthcheck:
          test: curl --fail http://localhost:3000/ || exit 1
          interval: 40s
          timeout: 30s
          retries: 3
          start_period: 60s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4-recipe
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db-postgre
  
  db-postgre:
    container_name: db-postgre
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
  